<?php
// HTTP RESPONSE
define('SERVER_OK', 200);

// ROLE
define('USER_ROLE', 1);
define('DRIVER_ROLE', 2);

// KODE REFERAL DAN SPONSOR DMS MOUGO
define('KODE_REFERAL_DMS',"RAAA000");
define('KODE_SPONSOR_DMS',"SAAA000");

// KODE REFERAL DAN SPONSOR USER
define('KODE_REFERAL_USER',"R");
define('KODE_SPONSOR_USER',"S");

// SALDO INFO
define('TAMBAH_SALDO',1);

// FUNGSI USER
define('REGISTER', 'register');
define('LOGIN', 'login');

// DRIVER 
define('STATUS_ONLINE',0);
define('STATUS_AKUN_AKTIF',0);
define('STATUS_AKTIF_USER',2);

// USER HITS, SALDO, POINT AWAL
define('HITS_AWAL',0);
define('SALDO_AWAL',0);
define('POINT_AWAL',0);

// HARGA 
define('HARGA_JARAK_MINIMAL',9000);
define('HARGA_JARAK_PERKILO',2000);

// JARAK MIN
define('JARAK_MINIMAL',2);

// STATUS TRIP
define('STATUS_MENCARI_DRIVER',1);
define('STATUS_DRIVER_MENJEMPUT',2);
define('STATUS_MENGANTAR_KETUJUAN',3);
define('STATUS_SAMPAI_TUJUAN',4);
define('STATUS_CANCEL',5);

// POSITION SET
define('POSITION_LAT',-2.980670100);
define('POSITION_LONG',104.726203500);

// DRIVER SILUMAN
define('ID_DRIVER_SILUMAN', "f768adacff6bb95eafb7d9a2d56be1c2f2ef6d13");